musique:
  root_dir: musique
  config_file: kag_config_knowledge_unit.yaml
  index_builder:
    type: benchmark_builder_musique
    file_path: data/sub_corpus.json
  qa_solver:
     type: benchmark_solver_musique
     upper_limit: 1
     qa_file_path: data/qa_sub.json

2wikimultihopqa:
  root_dir: 2wiki
  config_file: kag_config_knowledge_unit.yaml
  index_builder:
    type: benchmark_builder_2wiki
    file_path: data/sub_corpus.json
  qa_solver:
     type: benchmark_solver_2wiki
     upper_limit: 1
     qa_file_path: data/qa_sub.json

hotpotqa:
  root_dir: hotpotqa
  config_file: kag_config_knowledge_unit.yaml
  index_builder:
    type: benchmark_builder_hotpotqa
    file_path: data/sub_corpus.json
  qa_solver:
     type: benchmark_solver_hotpotqa
     upper_limit: 1
     qa_file_path: data/qa_sub.json
  
